version: '3.3'

services:
  dps-python:
    build:
      context: .
      dockerfile: ./docker/dps_python/prod.Dockerfile
    image: dps_python
  
  dps-manager:
    build:
      context: .
      dockerfile: ./docker/dps_manager/prod.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
#   command: gunicorn dps_manager.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./docker/dps_manager/prod.env
      - ./docker/dps_manager/prod.override.env
    restart: always      

  dps-manager-database:
    build:
      context: .
      dockerfile: ./docker/dps_manager_database/prod.Dockerfile
    env_file:
      - ./docker/dps_manager_database/prod.env
    restart: always      

  dps-database-manager:
    build:
      context: .
      dockerfile: ./docker/dps_database_manager/prod.Dockerfile
    env_file:
      - ./docker/dps_database_manager/prod.env
    restart: always            

  dps-database-manager-database:
    env_file:
      - ./docker/dps_database_manager_database/prod.env
    restart: always      

  dps-ui:
    ports:
      - 3005:3005
    environment:
      - PORT=3005
      - CHOKIDAR_USEPOLLING=true
    restart: always      
