version: '3.7'

services:
  dps-python:
    build:
      context: .
      dockerfile: ./docker/dps_python/dev.Dockerfile
    image: dps_python
      
  dps-manager:
    build:
      context: .
      dockerfile: ./docker/dps_manager/dev.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./dps_manager/:/usr/src/dps_manager/
      - ./dplib/:/usr/src/dplib/
      - ./dps_services/:/usr/src/dps_services/
      - ./dps_client/:/usr/src/dps_client/
    ports:
      - 8000:8000
    env_file:
      - ./docker/dps_manager/dev.env
    depends_on:
      - dps-python
      - dps-manager-database
      
  dps-manager-database:
    image: postgres:12.0-alpine
    volumes:
      - dps_manager_database:/var/lib/dps_manager_database/data/
    env_file:
      - ./docker/dps_manager_database/dev.env

  dps-ui:
    build:
      context: .
      dockerfile: ./docker/dps_ui/dev.Dockerfile
    stdin_open: true
    volumes:
      - ./dps_ui/:/usr/src/dps_ui
    ports:
      - 3005:3005
    environment:
      - PORT=3005

  dps-database-manager:
    build:
      context: .
      dockerfile: ./docker/dps_database_manager/dev.Dockerfile
    volumes:
      - ./dps_database_manager:/usr/src/dps_database_manager
      - ./dplib/:/usr/src/dplib/
      - ./dps_services/:/usr/src/dps_services/
      - ./dps_client/:/usr/src/dps_client/
    ports:
      - 3002:3002
    env_file:
      - ./docker/dps_database_manager/dev.env
    command: flask run --host=0.0.0.0 --with-threads --port=3002
    # Infinite loop, to keep it alive, for debugging
#    command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
    depends_on:
      - dps-python
      - dps-database-manager-database

  dps-database-manager-database:
    build:
      context: .
      dockerfile: ./docker/dps_database_manager_database/Dockerfile
    env_file:
      - ./docker/dps_database_manager_database/dev.env
    volumes:
      - dps_database_manager_database:/var/lib/dps_database_manager_database/data

volumes:
  dps_manager_database:
  dps_database_manager_database:
