version: '3.8'

# All volume definitions are in this override file
# to make it easier for production to not use volumes
# (they apparently slow containers down).
services:
  dps-manager:
    volumes:
      - ./dps_manager/:/usr/src/dps_manager/
      - ./dplib/:/usr/src/dplib/
      - ./dps_services/:/usr/src/dps_services/
      - ./dps_client/:/usr/src/dps_client/
     
  dps-manager-database:
    volumes:
      - dps_manager_database:/var/lib/dps_manager_database/data/

  dps-batch-processor-1:
    volumes:
      - ./dplib/:/usr/src/dplib/
      - ./dps_services/:/usr/src/dps_services/
      - ./dps_client/:/usr/src/dps_client/
      - ./dps_batch_processor/:/usr/src/dps_batch_processor/

  dps-batch-processor-2:
    volumes:
      - ./dplib/:/usr/src/dplib/
      - ./dps_services/:/usr/src/dps_services/
      - ./dps_client/:/usr/src/dps_client/
      - ./dps_batch_processor/:/usr/src/dps_batch_processor/

  dps-ui:
    volumes:
      - ./dps_ui/src/:/usr/src/dps_ui/src
      - ./dps_ui/public/:/usr/src/dps_ui/public
      - ./dps_ui/package.json:/usr/src/dps_ui/package.json
      - ./dps_ui/yarn.lock:/usr/src/dps_ui/yarn.lock

  dps-relay:
    volumes:
      - ./dps_relay/:/usr/src/dps_relay

  dps-database-manager:
    volumes:
      - ./dps_database_manager:/usr/src/dps_database_manager
      - ./dplib/:/usr/src/dplib/
      - ./dps_services/:/usr/src/dps_services/
      - ./dps_client/:/usr/src/dps_client/

  dps-database-manager-database:
    volumes:
      - dps_database_manager_database:/var/lib/dps_database_manager_database/data
