# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: insert.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='insert.proto',
  package='dps',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cinsert.proto\x12\x03\x64ps\x1a\x1fgoogle/protobuf/timestamp.proto\"-\n\rInsertRequest\x12\x1c\n\x07inserts\x18\x01 \x03(\x0b\x32\x0b.dps.Insert\"\x84\x01\n\x06Insert\x12\x0f\n\x07\x64\x61taset\x18\x01 \x01(\t\x12\x0f\n\x07signals\x18\x02 \x03(\t\x12\x1d\n\x07samples\x18\x03 \x01(\x0b\x32\x0c.dps.Samples\x12)\n\x05times\x18\x04 \x03(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06upsert\x18\x05 \x01(\x08\"&\n\x07Samples\x12\x1b\n\x07\x62\x61tches\x18\x01 \x03(\x0b\x32\n.dps.Batch\"\x16\n\x05\x42\x61tch\x12\r\n\x05value\x18\x02 \x03(\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_INSERTREQUEST = _descriptor.Descriptor(
  name='InsertRequest',
  full_name='dps.InsertRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='inserts', full_name='dps.InsertRequest.inserts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=99,
)


_INSERT = _descriptor.Descriptor(
  name='Insert',
  full_name='dps.Insert',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataset', full_name='dps.Insert.dataset', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signals', full_name='dps.Insert.signals', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='samples', full_name='dps.Insert.samples', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='times', full_name='dps.Insert.times', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upsert', full_name='dps.Insert.upsert', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=234,
)


_SAMPLES = _descriptor.Descriptor(
  name='Samples',
  full_name='dps.Samples',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='batches', full_name='dps.Samples.batches', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=274,
)


_BATCH = _descriptor.Descriptor(
  name='Batch',
  full_name='dps.Batch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='dps.Batch.value', index=0,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=298,
)

_INSERTREQUEST.fields_by_name['inserts'].message_type = _INSERT
_INSERT.fields_by_name['samples'].message_type = _SAMPLES
_INSERT.fields_by_name['times'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SAMPLES.fields_by_name['batches'].message_type = _BATCH
DESCRIPTOR.message_types_by_name['InsertRequest'] = _INSERTREQUEST
DESCRIPTOR.message_types_by_name['Insert'] = _INSERT
DESCRIPTOR.message_types_by_name['Samples'] = _SAMPLES
DESCRIPTOR.message_types_by_name['Batch'] = _BATCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InsertRequest = _reflection.GeneratedProtocolMessageType('InsertRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSERTREQUEST,
  '__module__' : 'insert_pb2'
  # @@protoc_insertion_point(class_scope:dps.InsertRequest)
  })
_sym_db.RegisterMessage(InsertRequest)

Insert = _reflection.GeneratedProtocolMessageType('Insert', (_message.Message,), {
  'DESCRIPTOR' : _INSERT,
  '__module__' : 'insert_pb2'
  # @@protoc_insertion_point(class_scope:dps.Insert)
  })
_sym_db.RegisterMessage(Insert)

Samples = _reflection.GeneratedProtocolMessageType('Samples', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLES,
  '__module__' : 'insert_pb2'
  # @@protoc_insertion_point(class_scope:dps.Samples)
  })
_sym_db.RegisterMessage(Samples)

Batch = _reflection.GeneratedProtocolMessageType('Batch', (_message.Message,), {
  'DESCRIPTOR' : _BATCH,
  '__module__' : 'insert_pb2'
  # @@protoc_insertion_point(class_scope:dps.Batch)
  })
_sym_db.RegisterMessage(Batch)


# @@protoc_insertion_point(module_scope)
