# Generated by Django 3.0.5 on 2020-10-05 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProcess',
            fields=[
                ('batch_process_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('kpi_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('identifier', models.CharField(max_length=200, null=True)),
                ('computation', models.TextField()),
                ('description', models.TextField(null=True)),
                ('hidden', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('system_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('parameter_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dps_manager_api.System')),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'SIGNAL'), (2, 'PARAMETER')])),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('batch_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dps_manager_api.BatchProcess')),
            ],
        ),
        migrations.CreateModel(
            name='KPIAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dps_manager_api.BatchProcess')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dps_manager_api.KPI')),
            ],
        ),
        migrations.AddField(
            model_name='kpi',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dps_manager_api.System'),
        ),
        migrations.CreateModel(
            name='BatchProcessProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField()),
                ('time', models.DateTimeField()),
                ('batch_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dps_manager_api.BatchProcess')),
            ],
        ),
    ]
