# Generated by Django 3.0.5 on 2020-10-06 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dps_manager_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='removed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='dps_manager_api.System'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='dps_manager_api.System'),
        ),
    ]
