# Generated by Django 3.0.5 on 2020-10-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dps_manager_api', '0003_auto_20201006_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='default',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='hidden',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='removed',
            field=models.BooleanField(null=True),
        ),
    ]
