# Generated by Django 3.0.5 on 2020-10-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dps_manager_api', '0004_auto_20201006_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
