# Generated by Django 3.0.5 on 2020-10-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dps_manager_api', '0006_auto_20201006_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='identifier',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
