# Generated by Django 3.0.5 on 2020-10-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dps_manager_api', '0007_parameter_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('ref', models.CharField(max_length=200, null=True)),
                ('kind', models.CharField(max_length=200)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='batchprocessprogress',
            name='batch_process',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='system',
        ),
        migrations.RemoveField(
            model_name='kpiassignment',
            name='batch_process',
        ),
        migrations.RemoveField(
            model_name='kpiassignment',
            name='kpi',
        ),
        migrations.RemoveField(
            model_name='mapping',
            name='batch_process',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='system',
        ),
        migrations.DeleteModel(
            name='BatchProcess',
        ),
        migrations.DeleteModel(
            name='BatchProcessProgress',
        ),
        migrations.DeleteModel(
            name='KPI',
        ),
        migrations.DeleteModel(
            name='KPIAssignment',
        ),
        migrations.DeleteModel(
            name='Mapping',
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
        migrations.DeleteModel(
            name='System',
        ),
    ]
