{
 "title": "Battery",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "KPIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Coulomb Efficiency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "battery_kpi",
     "query": "SELECT \"CurrentDischarge\" / \"CurrentCharge\" FROM\n(SELECT mean(\"Current\") as \"CurrentDischarge\" FROM \"battery_charge\" WHERE $timeFilter GROUP BY time($__interval) fill(none)),\n(SELECT mean(\"Current\") as \"CurrentCharge\" FROM \"battery_discharge\" WHERE $timeFilter GROUP BY time($__interval) fill(none));",
     "select": [
      [
       { "params": [ "BATT_CE" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Round Trip Energy Efficiency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Round Trip Energy Efficiency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "battery_kpi",
     "query": "SELECT \"CurrentDischarge\" / \"CurrentCharge\" FROM\n(SELECT mean(\"Current\") as \"CurrentDischarge\" FROM \"battery_charge\" WHERE $timeFilter GROUP BY time($__interval) fill(none)),\n(SELECT mean(\"Current\") as \"CurrentCharge\" FROM \"battery_discharge\" WHERE $timeFilter GROUP BY time($__interval) fill(none));",
     "select": [
      [
       { "params": [ "BATT_RTEE" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Capacity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "battery_kpi",
     "query": "SELECT \"CurrentDischarge\" / \"CurrentCharge\" FROM\n(SELECT mean(\"Current\") as \"CurrentDischarge\" FROM \"battery_charge\" WHERE $timeFilter GROUP BY time($__interval) fill(none)),\n(SELECT mean(\"Current\") as \"CurrentCharge\" FROM \"battery_discharge\" WHERE $timeFilter GROUP BY time($__interval) fill(none));",
     "select": [
      [
       { "params": [ "BATT_CAP" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "State of Health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "State of Health",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "battery_kpi",
     "query": "SELECT \"CurrentDischarge\" / \"CurrentCharge\" FROM\n(SELECT mean(\"Current\") as \"CurrentDischarge\" FROM \"battery_charge\" WHERE $timeFilter GROUP BY time($__interval) fill(none)),\n(SELECT mean(\"Current\") as \"CurrentCharge\" FROM \"battery_discharge\" WHERE $timeFilter GROUP BY time($__interval) fill(none));",
     "select": [
      [
       { "params": [ "BATT_SOH" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "From Simulation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "State of Charge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_kpi",
     "select": [
      [
       { "params": [ "Batt_SOC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "From Test File",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true
  },
  {
   "title": "Battery Charge",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "battery_discharge",
     "query": "SELECT mean(\"SOC\") as \"SOC\", mean(\"Voltage\") as \"Voltage\", mean(\"Current\") as \"Current\" FROM \"battery_charge\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "ESS.SOC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Discharge",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "battery_discharge",
     "query": "SELECT mean(\"SOC\") as \"SOC\", mean(\"Voltage\") as \"Voltage\", mean(\"Current\") as \"Current\" FROM \"battery_discharge\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "ESS.SOC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}