{
 "title": "PV Array",
 "time": { "from": "now-10s", "to": "now-0m" },
 "panels": [
  { "title": "PV Array", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Efficiency Power Electronics Inverter (Percent)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "PV_EInverter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT mean(\"PV_EInverter\") FROM \"pv_array_kpi\" WHERE $timeFilter AND \"PV_EInverter\" <= 100 AND \"PV_EInverter\" > 0 GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "PV_EInverter" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Efficiency Array (Percent)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "PV_EArray",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT mean(\"PV_EArray\") FROM \"pv_array_kpi\" WHERE $timeFilter AND \"PV_EArray\" <= 100 GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "PV_EArray" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fill Factor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Fill Factor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT mean(\"PV_FF\") FROM \"pv_array_kpi\" WHERE \"PV_FF\" <= 1.0 AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "PV_FF" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load (Percent)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "PV_LD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "select": [
      [
       { "params": [ "PV_LD" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "THD Current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "PV_THD_Ia",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT mean(\"PV_THD_Ia\") FROM \"pv_array_kpi\" WHERE $timeFilter AND \"PV_THD_Ia\" <= 1 GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "PV_THD_Ia" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PV_THD_Ib",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT mean(\"PV_THD_Ib\") FROM \"pv_array_kpi\" WHERE $timeFilter AND \"PV_THD_Ib\" <= 1 GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "PV_THD_Ib" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PV_THD_Ic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT mean(\"PV_THD_Ic\") FROM \"pv_array_kpi\" WHERE $timeFilter AND  \"PV_THD_Ic\" <= 1 GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "PV_THD_Ic" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "THD Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 9, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "PV_THD_Va",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT mean(\"PV_THD_Va\") FROM \"pv_array_kpi\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "PV_THD_Va" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PV_THD_Vb",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT mean(\"PV_THD_Vb\") FROM \"pv_array_kpi\" WHERE $timeFilter AND \"PV_THD_Vb\" <= 1 GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "PV_THD_Vb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PV_THD_Vc",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT mean(\"PV_THD_Vc\") FROM \"pv_array_kpi\" WHERE $timeFilter AND \"PV_THD_Vc\" <= 1 GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "PV_THD_Vc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Weighted Efficiency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT sum(*) FROM \n (SELECT median(\"PV_E\") * 0.04 FROM \"pv_array_kpi\" WHERE $timeFilter and \"PV_LD\" > 8 and \"PV_LD\" < 12),\n (SELECT median(\"PV_E\") * 0.05 FROM \"pv_array_kpi\" WHERE $timeFilter and \"PV_LD\" > 18 and \"PV_LD\" < 22),\n (SELECT median(\"PV_E\") * 0.12 FROM \"pv_array_kpi\" WHERE $timeFilter and \"PV_LD\" > 28 and \"PV_LD\" < 32),\n (SELECT median(\"PV_E\") * 0.21 FROM \"pv_array_kpi\" WHERE $timeFilter and \"PV_LD\" > 48 and \"PV_LD\" < 52),\n (SELECT median(\"PV_E\") * 0.53 FROM \"pv_array_kpi\" WHERE $timeFilter and \"PV_LD\" > 73 and \"PV_LD\" < 77),\n (SELECT median(\"PV_E\") * 0.05 FROM \"pv_array_kpi\" WHERE $timeFilter and \"PV_LD\" > 98);",
     "select": [
      [
       { "params": [ "PV_E" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "THD Voltage at Load Percentages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "THD Voltage (At 25% Load)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT \n    mean(\"PV_THD_Va\") as \"PV_THD_Va\", \n    mean(\"PV_THD_Vb\")  as \"PV_THD_Vb\",\n    mean(\"PV_THD_Vc\")  as \"PV_THD_Vc\"\nFROM \"pv_array_kpi\" WHERE $timeFilter  AND \"PV_LD\" > 20 AND \"PV_LD\" < 30 GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "PV_E" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "THD Voltage (At 50% Load)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT \n    mean(\"PV_THD_Va\") as \"PV_THD_Va\", \n    mean(\"PV_THD_Vb\")  as \"PV_THD_Vb\",\n    mean(\"PV_THD_Vc\")  as \"PV_THD_Vc\"\nFROM \"pv_array_kpi\" WHERE $timeFilter  AND \"PV_LD\" > 40 AND \"PV_LD\" < 60 GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "PV_E" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "THD Voltage (At 75% Load)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT\n    mean(\"PV_THD_Va\") as \"PV_THD_Va\", \n    mean(\"PV_THD_Vb\")  as \"PV_THD_Vb\",\n    mean(\"PV_THD_Vc\")  as \"PV_THD_Vc\" \nFROM \"pv_array_kpi\" \nWHERE $timeFilter  AND \"PV_LD\" > 65 AND \"PV_LD\" < 85 GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "PV_E" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "THD Voltage (At 100% Load)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT\n    mean(\"PV_THD_Va\") as \"PV_THD_Va\", \n    mean(\"PV_THD_Vb\")  as \"PV_THD_Vb\",\n    mean(\"PV_THD_Vc\")  as \"PV_THD_Vc\"\nFROM \"pv_array_kpi\" \nWHERE $timeFilter  AND \"PV_LD\" > 90 GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "PV_E" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "THD Current at Load Percentages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }
  },
  {
   "title": "THD Current (At 25% Load)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT \n    mean(\"PV_THD_Ia\") as \"PV_THD_Ia\", \n    mean(\"PV_THD_Ib\")  as \"PV_THD_Ib\",\n    mean(\"PV_THD_Ic\")  as \"PV_THD_Ic\"\nFROM \"pv_array_kpi\" WHERE $timeFilter  AND \"PV_LD\" > 20 AND \"PV_LD\" < 30 GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "PV_E" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "THD Current (At 50% Load)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT\n    mean(\"PV_THD_Ia\") as \"PV_THD_Ia\", \n    mean(\"PV_THD_Ib\")  as \"PV_THD_Ib\",\n    mean(\"PV_THD_Ic\")  as \"PV_THD_Ic\"\n FROM \"pv_array_kpi\" WHERE $timeFilter  AND \"PV_LD\" > 40 AND \"PV_LD\" < 60 GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "PV_E" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "THD Current (At 75% Load)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT\n    mean(\"PV_THD_Ia\") as \"PV_THD_Ia\", \n    mean(\"PV_THD_Ib\")  as \"PV_THD_Ib\",\n    mean(\"PV_THD_Ic\")  as \"PV_THD_Ic\"\nFROM \"pv_array_kpi\" \nWHERE $timeFilter  AND \"PV_LD\" > 65 AND \"PV_LD\" < 85 GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "PV_E" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "THD Current (At 100% Load)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT\n    mean(\"PV_THD_Ia\") as \"PV_THD_Ia\", \n    mean(\"PV_THD_Ib\")  as \"PV_THD_Ib\",\n    mean(\"PV_THD_Ic\")  as \"PV_THD_Ic\"\nFROM \"pv_array_kpi\" \nWHERE $timeFilter  AND \"PV_LD\" > 90 GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "PV_E" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Weighted Efficiency Components", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Weighted Efficiency (10%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT median(\"PV_E\") * 0.04 FROM \"pv_array_kpi\" WHERE $timeFilter  and \"PV_LD\" > 8 and \"PV_LD\" < 12",
     "select": [
      [
       { "params": [ "PV_E" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Weighted Efficiency (20%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT median(\"PV_E\") * 0.05 FROM \"pv_array_kpi\" WHERE $timeFilter  and \"PV_LD\" > 18 and \"PV_LD\" < 22",
     "select": [
      [
       { "params": [ "PV_E" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Weighted Efficiency (30%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT median(\"PV_E\") * 0.12 FROM \"pv_array_kpi\" WHERE $timeFilter  and \"PV_LD\" > 28 and \"PV_LD\" < 32",
     "select": [
      [
       { "params": [ "PV_E" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Weighted Efficiency (50%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT median(\"PV_E\") * 0.21 FROM \"pv_array_kpi\" WHERE $timeFilter  and \"PV_LD\" > 48 and \"PV_LD\" < 52",
     "select": [
      [
       { "params": [ "PV_E" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Weighted Efficiency (75%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT median(\"PV_E\") * 0.53 FROM \"pv_array_kpi\" WHERE $timeFilter  and \"PV_LD\" > 73 and \"PV_LD\" < 77",
     "select": [
      [
       { "params": [ "PV_E" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Weighted Efficiency (100%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv_array_kpi",
     "query": "SELECT median(\"PV_E\") * 0.05 FROM \"pv_array_kpi\" WHERE $timeFilter  and \"PV_LD\" > 98",
     "select": [
      [
       { "params": [ "PV_E" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Array (Raw Signals)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Currents",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "PV_Ia",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "signals",
       "select": [
        [
         { "params": [ "PV_Ia" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "PV_Ib",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "signals",
       "select": [
        [
         { "params": [ "PV_Ib" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "PV_Ic",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "signals",
       "select": [
        [
         { "params": [ "PV_Ic" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Voltages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Va",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "signals",
       "select": [
        [
         { "params": [ "PV_Va" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Vb",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "signals",
       "select": [
        [
         { "params": [ "PV_Vb" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Vc",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "signals",
       "select": [
        [
         { "params": [ "PV_Vc" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "PV_Vmp and PV_Imp",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "PV_Vmp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "signals",
       "select": [
        [
         { "params": [ "PV_Vmp" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "PV_Imp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "signals",
       "select": [
        [
         { "params": [ "PV_Imp" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "PV_Pmax, PV_Pin, PV_Pout",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 8, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "PV_Pin",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "pv_array_kpi",
       "query": "SELECT mean(\"PV_Pin\") FROM \"pv_array_kpi\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "PV_Pin" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "PV_Pout",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "pv_array_kpi",
       "select": [
        [
         { "params": [ "PV_Pout" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "PV_Pmax",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "pv_array_kpi",
       "query": "SELECT mean(\"PV_Pin\") FROM \"pv_array_kpi\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "PV_Pmax" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}