{
 "title": "Wind Turbine",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Wind Turbine Efficiency (Percent)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Efficiency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wind_kpi",
     "query": "SELECT mean(\"WD_E\") FROM \"wind_kpi\" WHERE $timeFilter AND \"WD_E\" >= 0 AND \"WD_E\" <= 50 GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "WD_E" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load (Percent)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wind_kpi",
     "query": "SELECT mean(\"WD_LD\") FROM \"wind_kpi\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "WD_E" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "THD Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "WD_THD_Va",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wind_kpi",
     "select": [
      [
       { "params": [ "WD_THD_Va" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "WD_THD_Vb",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wind_kpi",
     "select": [
      [
       { "params": [ "WD_THD_Vb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "WD_THD_Vc",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wind_kpi",
     "select": [
      [
       { "params": [ "WD_THD_Vc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current THD",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "WD_THD_Ia",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wind_kpi",
     "query": "SELECT mean(\"WD_THD_Ia\") FROM \"wind_kpi\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "WD_THD_Ia" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "WD_THD_Ib",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wind_kpi",
     "query": "SELECT mean(\"WD_THD_Ib\") FROM \"wind_kpi\" WHERE $timeFilter AND \"WD_THD_Ib\" <= 1 GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "WD_THD_Ib" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "WD_THD_Ic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wind_kpi",
     "query": "SELECT mean(\"WD_THD_Ic\") FROM \"wind_kpi\" WHERE $timeFilter AND \"WD_THD_Ic\" <= 1 GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "WD_THD_Ic" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "THD Voltage at Load Percentages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "THD Voltage (At 25% Load)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \n    mean(\"WD_THD_Va\") as \"WD_THD_Va\", \n    mean(\"WD_THD_Vb\")  as \"WD_THD_Vb\",\n    mean(\"WD_THD_Vc\")  as \"WD_THD_Vc\"\nFROM \"wind_kpi\" WHERE $timeFilter  AND \"WD_LD\" > 20 AND \"WD_LD\" < 30 GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "THD Voltage (At 50% Load)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \n    mean(\"WD_THD_Va\") as \"WD_THD_Va\", \n    mean(\"WD_THD_Vb\")  as \"WD_THD_Vb\",\n    mean(\"WD_THD_Vc\")  as \"WD_THD_Vc\"\nFROM \"wind_kpi\" WHERE $timeFilter  AND \"WD_LD\" > 40 AND \"WD_LD\" < 60 GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "THD Voltage (At 75% Load)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \n    mean(\"WD_THD_Va\") as \"WD_THD_Va\", \n    mean(\"WD_THD_Vb\")  as \"WD_THD_Vb\",\n    mean(\"WD_THD_Vc\")  as \"WD_THD_Vc\"\nFROM \"wind_kpi\" WHERE $timeFilter  AND \"WD_LD\" > 65 AND \"WD_LD\" < 85 GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "THD Voltage (At 100% Load)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \n    mean(\"WD_THD_Va\") as \"WD_THD_Va\", \n    mean(\"WD_THD_Vb\")  as \"WD_THD_Vb\",\n    mean(\"WD_THD_Vc\")  as \"WD_THD_Vc\"\nFROM \"wind_kpi\" WHERE $timeFilter  AND \"WD_LD\" > 90 AND \"WD_LD\" <= 100 GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "THD Current at Load Percentages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "title": "THD Current (At 25% Load)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \n    mean(\"WD_THD_Ia\") as \"WD_THD_Ia\", \n    mean(\"WD_THD_Ib\")  as \"WD_THD_Ib\",\n    mean(\"WD_THD_Ic\")  as \"WD_THD_Ic\"\nFROM \"wind_kpi\" WHERE $timeFilter  AND \"WD_LD\" > 20 AND \"WD_LD\" < 30 GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "THD Current (At 50% Load)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \n    mean(\"WD_THD_Ia\") as \"WD_THD_Ia\", \n    mean(\"WD_THD_Ib\")  as \"WD_THD_Ib\",\n    mean(\"WD_THD_Ic\")  as \"WD_THD_Ic\"\nFROM \"wind_kpi\" WHERE $timeFilter  AND \"WD_LD\" > 40 AND \"WD_LD\" < 60 GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "THD Current (At 75% Load)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \n    mean(\"WD_THD_Ia\") as \"WD_THD_Ia\", \n    mean(\"WD_THD_Ib\")  as \"WD_THD_Ib\",\n    mean(\"WD_THD_Ic\")  as \"WD_THD_Ic\"\nFROM \"wind_kpi\" WHERE $timeFilter  AND \"WD_LD\" > 65 AND \"WD_LD\" < 85 GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "THD Current (At 100% Load)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \n    mean(\"WD_THD_Ia\") as \"WD_THD_Ia\", \n    mean(\"WD_THD_Ib\")  as \"WD_THD_Ib\",\n    mean(\"WD_THD_Ic\")  as \"WD_THD_Ic\"\nFROM \"wind_kpi\" WHERE $timeFilter  AND \"WD_LD\" > 90 AND \"WD_LD\" <= 100 GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Weighted Efficiency Components",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Weighted Efficiency (10%)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT median(\"WD_E\") * 0.04 FROM \"wind_kpi\" WHERE $timeFilter and \"WD_LD\" > 8 and \"WD_LD\" < 12",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Weighted Efficiency (20%)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT median(\"WD_E\") * 0.05 FROM \"wind_kpi\" WHERE $timeFilter and \"WD_LD\" > 18 and \"WD_LD\" < 22",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Weighted Efficiency (30%)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 58 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT median(\"WD_E\") * 0.12 FROM \"wind_kpi\" WHERE $timeFilter and \"WD_LD\" > 28 and \"WD_LD\" < 32",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Weighted Efficiency (50%)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 58 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT median(\"WD_E\") * 0.21 FROM \"wind_kpi\" WHERE $timeFilter and \"WD_LD\" > 48 and \"WD_LD\" < 52",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Weighted Efficiency",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 66 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(*) FROM \n (SELECT median(\"WD_E\") * 0.04 FROM \"wind_kpi\" WHERE $timeFilter and \"WD_LD\" > 8 and \"WD_LD\" < 12),\n (SELECT median(\"WD_E\") * 0.05 FROM \"wind_kpi\" WHERE $timeFilter and \"WD_LD\" > 18 and \"WD_LD\" < 22),\n (SELECT median(\"WD_E\") * 0.12 FROM \"wind_kpi\" WHERE $timeFilter and \"WD_LD\" > 28 and \"WD_LD\" < 32),\n (SELECT median(\"WD_E\") * 0.21 FROM \"wind_kpi\" WHERE $timeFilter and \"WD_LD\" > 48 and \"WD_LD\" < 52),\n (SELECT median(\"WD_E\") * 0.53 FROM \"wind_kpi\" WHERE $timeFilter and \"WD_LD\" > 73 and \"WD_LD\" < 77),\n (SELECT median(\"WD_E\") * 0.05 FROM \"wind_kpi\" WHERE $timeFilter and \"WD_LD\" > 98);",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Weighted Efficiency (75%)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 73 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT median(\"WD_E\") * 0.53 FROM \"wind_kpi\" WHERE $timeFilter and \"WD_LD\" > 73 and \"WD_LD\" < 77",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Weighted Efficiency (100%)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 73 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT median(\"WD_E\") * 0.05 FROM \"wind_kpi\" WHERE $timeFilter and \"WD_LD\" > 98",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Signals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wind Velocity",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "signals",
       "select": [
        [
         {
          "params": [
           "Wind Power Plant (Switching).Control.Grid_follow.wind_speed"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Voltage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "WD_Va",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "signals",
       "select": [
        [
         { "params": [ "Wd_Va" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "WD_Vb",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "signals",
       "select": [
        [
         { "params": [ "Wd_Vb" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "WD_Vc",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "signals",
       "select": [
        [
         { "params": [ "Wd_Vc" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Current",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "WD_Ia",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "signals",
       "select": [
        [
         { "params": [ "Wd_Ia" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "WD_Ib",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "signals",
       "select": [
        [
         { "params": [ "Wd_Ib" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "WD_Ic",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "signals",
       "select": [
        [
         { "params": [ "Wd_Ic" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}