* KPI CSV

This directory contains an example usage of ~dplib~ which runs several KPI computations on some (mocked) input data.

To run the code, first install the dependencies for the project. Install 3rd party dependencies by running:

#+BEGIN_SRC shell
pip3 install -r requirements.txt
#+END_SRC

Then install the ~dps_services~ package, by navigating to ~dps/dps_services~ (where dps is the root of this git repository), and run:

#+BEGIN_SRC shell
pip3 install . --upgrade
#+END_SRC

The upgrade flag is to ensure you are forcing an upgrade if you have already installed the package (with the same version).

** Generating data.csv
I have included ~data.csv~ in the git repository, so this step is optional.

The ~gen.py~ file is used for generating the input data. This is not important in demonstrating ~dplib~, it is simply to generate the ~data.csv~ file.
It can be run via:

#+BEGIN_SRC shell
python3 gen.py
#+END_SRC

(While you are in this directory (in a command line)).

** Running KPIs
The ~main.py~ file reads ~data.csv~, runs several KPIs, and writes the results to ~kpis.csv~. To run this file:

#+BEGIN_SRC shell
python3 main.py
#+END_SRC

(Ensure your shell has navigated to this directory).

After running, ~kpis.csv~ will be written to the file system (in this directory). I have included an existing ~kpis.csv~ in the git repository.
This is simply for those who want to see the results without running. To make sure you are viewing the KPIs you just computed, you can
remove ~kpis.csv~ before running ~main.py~, then run ~main.py~.
